### ISSUE TITLE
CI Checklist for Github Actions

### ISSUE THREAD

**Issue by jacksgt** [martialblog/docker-limesurvey#69]
_Originally posted by @martialblog in https://github.com/martialblog/docker-limesurvey/issues/68#issuecomment-864368908_

What I currently imagine for the CI is this:

- [x] hadolint runs on all branches/PR
- [x] Images are build on all branches/PR
- [x] Container structure tests on all branches/PR
- [x] Trivy Scan on Tags (report as artifact) (see #67)
- [x] Push on Tags

**Comment by jacksgt** [comment]
This could also utilize an external build cache for the image build, see [docker-build action](https://github.com/docker/build-push-action/blob/master/docs/advanced/cache.md).

**Comment by martialblog** [comment]
@jacksgt  I just merged your Branch. Thanks again for the great work!

I already added hadolint Jobs. Next will be structure tests and trivy scan. 

Cheers
Markus

**Comment by martialblog** [comment]
Why do I think that this Error: `invalid tag "docker.io/***/limesurvey:5.0.4+210614-apache"` is because the Secret DOCKER_USERNAME is replaced with `***` ?

**Comment by jacksgt** [comment]
Haha, hunter2 strikes again.
The DOCKER_USERNAME is replaced before logging the output, but not before execution
But that is not the problem.
The issue is the `+` in the tag.

**Comment by martialblog** [comment]
Ah ok NOW I see what you meant. Hm that's unfortunate... I gotta update the update.sh then, cause I simply used the LS Tags.

**Comment by jacksgt** [comment]
:sweat_smile: 

I mean, we could also add another build step that string-replaces `+` with `_` automatically (so we get the same behavior as before).
But IMO, it was already kind of weird that the Git tag (on Github) is `5.0.3+foobar` but the tag on DockerHub is `5.0.3_foobar` (apparently DockerHub did this automatically?).
At least now it will be consistent :-)

**Comment by martialblog** [comment]
I totally agree with `+` Tags are strange. I just used because I wanted the users to have the same schema as the LS Version. 

Dashes are fine, everybody loves dashes... except Python Modules... and Yaml Keys. But those are barely used in OSS.

**Comment by martialblog** [comment]
I think we're good? are we good? Anything else?

**Comment by jacksgt** [comment]
Caching is still missing, but we can open a separate issue for that and attach to the GHA milestone.

**Comment by martialblog** [comment]
Yes I agree. Could take a while until the kinks are fixed upstream
